_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 20000

model:
  type: DeepLabV2
  backbone:
    type: ResNet101_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  backbone_indices: [3]
  aspp_ratios: [6, 12, 18, 24]
  align_corners: False
  pretrained: null